"""TraceFix 公共 API。"""

from tracefix.agent import (
    DEFAULT_SYSTEM_PROMPT,
    AgentConfig,
    AgentState,
    AgentStatus,
    BaseAgent,
    MinimalAgent,
)
from tracefix.exceptions import (
    AgentCompleted,
    AgentError,
    AgentInterrupted,
    AgentLimitExceeded,
    LLMAuthenticationError,
    LLMContextWindowError,
    LLMError,
    LLMProviderError,
    LLMRateLimitError,
    LLMResponseFormatError,
    LLMTimeoutError,
    MessageProtocolError,
    StepLimitExceeded,
    TestLimitExceeded,
    TimeLimitExceeded,
    TokenBudgetExceeded,
    ToolAlreadyRegisteredError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolTimeoutError,
    ToolValidationError,
    TraceFixError,
    TraceProtocolError,
)
from tracefix.messages import Message, MessageHistory, MessageRole, ToolCall
from tracefix.models import BaseLLM, LiteLLMAdapter, LLMConfig, LLMResponse, TokenUsage
from tracefix.tools import (
    RESERVED_TOOL_NAMES,
    ApplyPatchTool,
    BaseTool,
    GetGitDiffTool,
    ReadFileTool,
    ReservedToolName,
    RunTestsTool,
    SearchCodeTool,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    create_default_tool_registry,
)
from tracefix.tracing import TraceEvent, TraceEventType, TraceSink

__version__ = "0.1.0"

__all__ = [
    "RESERVED_TOOL_NAMES",
    "DEFAULT_SYSTEM_PROMPT",
    "AgentCompleted",
    "AgentConfig",
    "AgentError",
    "AgentInterrupted",
    "AgentLimitExceeded",
    "AgentState",
    "AgentStatus",
    "ApplyPatchTool",
    "BaseAgent",
    "BaseLLM",
    "BaseTool",
    "GetGitDiffTool",
    "LLMAuthenticationError",
    "LLMConfig",
    "LLMContextWindowError",
    "LLMError",
    "LLMProviderError",
    "LLMRateLimitError",
    "LLMResponse",
    "LLMResponseFormatError",
    "LLMTimeoutError",
    "LiteLLMAdapter",
    "MinimalAgent",
    "Message",
    "MessageHistory",
    "MessageProtocolError",
    "MessageRole",
    "ReservedToolName",
    "ReadFileTool",
    "RunTestsTool",
    "SearchCodeTool",
    "StepLimitExceeded",
    "TestLimitExceeded",
    "TimeLimitExceeded",
    "TokenBudgetExceeded",
    "TokenUsage",
    "ToolAlreadyRegisteredError",
    "ToolCall",
    "ToolError",
    "ToolExecutionError",
    "ToolNotFoundError",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolTimeoutError",
    "ToolValidationError",
    "TraceEvent",
    "TraceEventType",
    "TraceFixError",
    "TraceProtocolError",
    "TraceSink",
    "__version__",
    "create_default_tool_registry",
]
