"""Offline inventory and repeat acceptance of frozen development patches."""

from __future__ import annotations

import argparse
import getpass
import hashlib
import json
import platform
import re
import subprocess
import sys
from pathlib import Path
from uuid import uuid4

from tracefix.provenance import inspect_test_environment
from tracefix.real_benchmark import load_real_issue_tasks
from tracefix.real_environment import resolve_managed_environment_python
from tracefix.real_experiment import validate_agent_patch_strict, validate_real_task_behavior
from tracefix.real_recipes import load_environment_recipes

EXPERIMENT = Path("runs/no-effect-recovery-paid-development-20260926-v1/experiment")
DIAGNOSIS = Path("docs/reviews/2026-09-26-throughput-diagnostic.json")
TASKS = Path("benchmarks/real_candidates")
RECIPES = Path("benchmarks/real_recipes")
SOURCES = Path("runs/real-candidate-validation-v080b")
ENVIRONMENTS = Path("runs/p1-revalidation-20260917/environments")
RUNNER_FILE = re.compile(
    r"\.tracefix-test-tmp/(?:agent-audit-[0-9a-f]{32}\.json|"
    r"agent-junit-[0-9a-f]{32}\.xml|tracefix_agent_audit\.py)"
)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def isolate_product_patch(source: Path, destination: Path) -> dict:
    """Strip only exact files generated by the historical test runner."""
    chunks = re.split(rb"(?=^diff --git a/)", source.read_bytes(), flags=re.MULTILINE)
    kept, internal = [], []
    for chunk in chunks:
        match = re.match(rb"diff --git a/(.+?) b/(.+?)\r?\n", chunk)
        if match:
            old, new = (part.decode("utf-8", "replace") for part in match.groups())
            if old == new and RUNNER_FILE.fullmatch(old):
                internal.append(old)
                continue
        kept.append(chunk)
    product = b"".join(kept)
    if product.strip():
        destination.write_bytes(product)
    return {
        "raw_sha256": sha(source),
        "product_sha256": hashlib.sha256(product).hexdigest(),
        "product_bytes": len(product),
        "removed_runner_files": internal,
        "product_patch_path": str(destination) if product.strip() else None,
    }


def inventory(experiment: Path, output: Path) -> list[dict]:
    positions = json.loads(DIAGNOSIS.read_text(encoding="utf-8"))["positions"]
    issues = {position["sequence"]: position for position in positions}
    patch_dir = output / "derived-product-patches"
    patch_dir.mkdir(exist_ok=True)
    rows = []
    for path in sorted((experiment / "trials").glob("[0-9][0-9][0-9].json")):
        trial = json.loads(path.read_text(encoding="utf-8"))
        sequence = trial["sequence"]
        patch = Path(trial["agent_patch_path"])
        if sha(patch) != trial["agent_patch_sha256"]:
            raise ValueError(f"frozen patch hash mismatch: {sequence}")
        derived = isolate_product_patch(patch, patch_dir / f"{sequence:03}.diff")
        original = issues[sequence]
        rows.append(
            {
                "sequence": sequence,
                "task_id": trial["task_id"],
                "arm": trial["arm"],
                "original_category": original["raw_category"],
                "original_reason": original["raw_verification_reason"],
                "original_evidence_valid": original["evidence_valid"],
                "original_trial_sha256": sha(path),
                "historical_patch": derived,
                "derived_outcome": "no_product_change"
                if not derived["product_patch_path"]
                else "unverified",
            }
        )
    if len(rows) != 48:
        raise ValueError(f"expected 48 positions, got {len(rows)}")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--stage", choices=("inventory", "qualification", "patches"), required=True)
    parser.add_argument("--tasks", nargs="*", default=[])
    parser.add_argument("--sequences", type=int, nargs="*", default=[])
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()
    output, experiment = args.output.resolve(), EXPERIMENT.resolve()
    if experiment == output or experiment in output.parents:
        raise ValueError("output must be outside frozen evidence")
    if output.exists() != args.resume:
        raise ValueError("use a new directory, or --resume for an existing one")
    selected = set(args.tasks)
    output.mkdir(parents=True, exist_ok=args.resume)
    prior_report = output / "report.json"
    if args.resume and prior_report.is_file():
        prior = json.loads(prior_report.read_text(encoding="utf-8"))
        if (
            prior.get("experiment_protocol_sha256") != sha(experiment / "protocol.json")
            or prior.get("diagnosis_sha256") != sha(DIAGNOSIS)
        ):
            raise ValueError("cannot resume after frozen protocol or diagnosis changed")
    rows = inventory(experiment, output)
    selected.update(row["task_id"] for row in rows if row["sequence"] in args.sequences)
    if args.stage != "inventory" and not selected:
        raise ValueError("explicit task or sequence selection required")
    tasks = (
        {task.id: task for task in load_real_issue_tasks(TASKS, task_ids=tuple(selected))}
        if selected
        else {}
    )
    recipes = load_environment_recipes(RECIPES)
    protocol = json.loads((experiment / "protocol.json").read_text(encoding="utf-8"))
    progress = output / "progress.json"
    executions = (
        json.loads(progress.read_text(encoding="utf-8"))
        if args.resume and progress.is_file()
        else []
    )
    completed = {(item["task_id"], item["sequence"], item["repeat"]) for item in executions}
    for task_id in sorted(selected):
        task, recipe = tasks[task_id], recipes[task_id]
        source = (SOURCES / task_id).resolve()
        task.validate_checkout(source)
        cleanliness = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=all"],
            cwd=source, capture_output=True, text=True, check=False,
        )
        if cleanliness.returncode or cleanliness.stdout.strip():
            raise ValueError(f"frozen source checkout is not clean: {task_id}")
        python = resolve_managed_environment_python(ENVIRONMENTS, task_id)
        fingerprint = inspect_test_environment(
            python, pythonpath_entries=task.test_pythonpath_paths
        ).fingerprint_sha256
        if fingerprint != protocol["p1_qualifications"][task_id]["dependency_fingerprint"]:
            raise ValueError(f"frozen dependency identity changed: {task_id}")
        if args.stage == "qualification":
            jobs = [(None, repeat) for repeat in (1, 2)]
        elif args.stage == "patches":
            jobs = [
                (row, repeat)
                for row in rows
                if row["task_id"] == task_id
                and (not args.sequences or row["sequence"] in args.sequences)
                and row["historical_patch"]["product_patch_path"]
                for repeat in (1, 2)
            ]
        else:
            jobs = []
        for row, repeat in jobs:
            sequence = row["sequence"] if row else None
            if (task_id, sequence, repeat) in completed:
                continue
            identity = task_id if row is None else f"{row['sequence']:03}"
            destination = output / f"{args.stage}-{identity}-{repeat}"
            if destination.exists():
                destination = output / f"{args.stage}-{identity}-{repeat}-resume-{uuid4().hex[:8]}"
            try:
                if row is None:
                    result = validate_real_task_behavior(
                        task,
                        source=source,
                        test_python=python,
                        output_dir=destination,
                        recipe=recipe,
                    )
                else:
                    result = validate_agent_patch_strict(
                        task,
                        source=source,
                        agent_patch=Path(row["historical_patch"]["product_patch_path"]),
                        test_python=python,
                        output_dir=destination,
                        recipe=recipe,
                        expected_node_ids=tuple(
                            protocol["p1_qualifications"][task_id]["expected_node_ids"]
                        ),
                        environment_variables=recipe.environment_variables,
                    )
                data = result.model_dump(mode="json")
            except Exception as exc:
                data = {"error_type": type(exc).__name__, "error": str(exc)}
            executions.append(
                {
                    "task_id": task_id,
                    "sequence": row["sequence"] if row else None,
                    "repeat": repeat,
                    "result": data,
                }
            )
            progress.write_text(
                json.dumps(executions, ensure_ascii=False, indent=2), encoding="utf-8"
            )
    report = {
        "kind": "frozen_patch_reverification",
        "experiment_protocol_sha256": sha(experiment / "protocol.json"),
        "diagnosis_sha256": sha(DIAGNOSIS),
        "runtime": {
            "user": getpass.getuser(),
            "python": sys.executable,
            "python_version": platform.python_version(),
            "platform": platform.platform(),
        },
        "task_inputs": {
            task_id: {
                "base_commit": tasks[task_id].base_commit,
                "test_patch_sha256": sha(tasks[task_id].test_patch_path),
                "gold_patch_sha256": sha(tasks[task_id].gold_patch_path),
                "recipe_fingerprint": recipes[task_id].fingerprint,
                "test_python": str(resolve_managed_environment_python(ENVIRONMENTS, task_id)),
                "frozen_dependency_fingerprint": protocol["p1_qualifications"][task_id][
                    "dependency_fingerprint"
                ],
            }
            for task_id in sorted(selected)
        },
        "rows": rows,
        "executions": executions,
    }
    (output / "report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(output / "report.json")


if __name__ == "__main__":
    main()
